workflows:
  ios-workflow:
    name: Jeyx de Qvebec Explorer
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: JeyxDeQvebecExplorerAPIKey
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.JeuxDeQuebec.jeuxDeQuebec
      vars:
        BUNDLE_ID: com.JeuxDeQuebec.jeuxDeQuebec
        XCODE_WORKSPACE: JeuxdeQuebec.xcworkspace
        XCODE_SCHEME: JeuxdeQuebec
        APP_STORE_APPLE_ID: 6740582360
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up provisioning profiles
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/Build/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/Build/*.dSYM
    publishing:
          app_store_connect:
            auth: integration
            submit_to_app_store: true
            copyright: Jeyx de Qvebec Explorer 2025